// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI9HVs70jJynhnP-fBLAVSy_rKQsA1hc',
    appId: '1:969861703619:web:c03063f20de3cd6fbcbf76',
    messagingSenderId: '969861703619',
    projectId: 'somativa-fire1102',
    authDomain: 'somativa-fire1102.firebaseapp.com',
    storageBucket: 'somativa-fire1102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hfipTtHz4-pm8dbf63V8F1G_7kgaWJ0',
    appId: '1:969861703619:android:0ae50b623fa5e82fbcbf76',
    messagingSenderId: '969861703619',
    projectId: 'somativa-fire1102',
    storageBucket: 'somativa-fire1102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm5rpm1_cmatYMsx2G5vHF-fmA7YK0FbY',
    appId: '1:969861703619:ios:7d34b08004b0e6fabcbf76',
    messagingSenderId: '969861703619',
    projectId: 'somativa-fire1102',
    storageBucket: 'somativa-fire1102.firebasestorage.app',
    iosBundleId: 'com.example.somativaFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm5rpm1_cmatYMsx2G5vHF-fmA7YK0FbY',
    appId: '1:969861703619:ios:7d34b08004b0e6fabcbf76',
    messagingSenderId: '969861703619',
    projectId: 'somativa-fire1102',
    storageBucket: 'somativa-fire1102.firebasestorage.app',
    iosBundleId: 'com.example.somativaFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWI9HVs70jJynhnP-fBLAVSy_rKQsA1hc',
    appId: '1:969861703619:web:0e54cc2c19fe638dbcbf76',
    messagingSenderId: '969861703619',
    projectId: 'somativa-fire1102',
    authDomain: 'somativa-fire1102.firebaseapp.com',
    storageBucket: 'somativa-fire1102.firebasestorage.app',
  );
}
